export type AILocation = {
  latitude: number;
  longitude: number;
  city?: string;
  region?: string; // state/province
  country: string; // ISO 3166-1 alpha-2 code (e.g., "US")
};

export type AIInsights = {
  name: string | null;
  description: string | null;
  features: string[] | null;
  parking: string | null;
  sources: string[] | null;
  images:
    | {
        image_url: string;
        origin_url: string;
        height: number;
        width: number;
      }[]
    | null;
  accessibility: string[] | null;
  // Tier rating (determined by Gemini AI based on features, uniqueness, destination quality)
  tier: "neighborhood" | "gem" | "star" | null;
  tier_reasoning: string | null; // Why Gemini assigned this tier
  // Image search queries (generated by Gemini AI for optimal image search)
  image_search_queries: string[] | null;
};
