export const playgrounds = [
  {
    id: 1,
    name: "Central Park Playground",
    address: "Central Park, New York, NY",
    distance: "0.5 miles",
    rating: 4.8,
    reviews: 124,
    ageRange: "2-12",
    features: ["Swings", "Slides", "Sand"],
    access: "Free",
    image: "/playground-placeholder.svg?height=200&width=300",
    bookmarked: true,
  },
  {
    id: 2,
    name: "Riverside Playground",
    address: "Riverside Dr, New York, NY",
    distance: "0.8 miles",
    rating: 4.5,
    reviews: 89,
    ageRange: "0-5",
    features: ["Swings", "Slides"],
    access: "Free",
    image: "/playground-placeholder.svg?height=200&width=300",
    bookmarked: false,
  },
  {
    id: 3,
    name: "Community Garden Playground",
    address: "Garden St, New York, NY",
    distance: "1.2 miles",
    rating: 4.2,
    reviews: 56,
    ageRange: "4-10",
    features: ["Slides", "Sand"],
    access: "Community",
    image: "/playground-placeholder.svg?height=200&width=300",
    bookmarked: false,
  },
  {
    id: 4,
    name: "Adventure Playground",
    address: "Adventure Ave, New York, NY",
    distance: "1.5 miles",
    rating: 4.9,
    reviews: 210,
    ageRange: "5-15",
    features: ["Swings", "Slides", "Climbing"],
    access: "Paid",
    image: "/playground-placeholder.svg?height=200&width=300",
    bookmarked: true,
  },
];
